apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      imagePullSecrets:
        - name: docker-key
      containers:
        - name: master
          image: systemywp/master:client_v1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-srv
spec:
  type: ClusterIP
  selector:
    app: client-app
  ports:
    - name: client-app
      protocol: TCP
      port: 80
      targetPort: 80